version: '3.1'

services:
  db:
    image: postgres
    container_name: db_spent
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: spent-app
      POSTGRES_PASSWORD: spent-app
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql

  api:
    container_name: spent-app
    image: spent:1.9.0
    expose:
      - 8080
    ports:
      - "8080:8080"
    volumes:
      - /tmp/_cache:/app/_cache
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/spent-app
      SPRING_DATASOURCE_USERNAME: spent-app
      SPRING_DATASOURCE_PASSWORD: spent-app
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

