spring:
  application:
    name: spent-api

  datasource:
    url: '${DATABASE_URL}'
    username: '${PGUSER}'
    password: '${PGPASSWORD}'
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
server:
  servlet:
    context-path: /api

springdoc:
  api-docs:
    path: /api-docs
