spring:
  application:
    name: spent-api

  datasource:
    url: jdbc:postgresql://localhost:5432/SPENT-APP
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
server:
  servlet:
    context-path: /api

springdoc:
  api-docs:
    path: /api-docs
